### ISSUE TITLE
SyntaxError: 'async with' outside async function

### ISSUE THREAD

**Issue by liljoycel** [ergoncugler/web-scraping-telegram#1]
hi, please i need help to run this project!

 File "C:\Users\xx\Downloads\Compressed\web-scraping-telegram-main\web-scraping-telegram-main\main.py", line 57
    async with TelegramClient(username, api_id, api_hash) as client:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: 'async with' outside async function

**Comment by ergoncugler** [comment]
Hello! I have released a new version of the code: [https://github.com/ergoncugler/web-scraping-telegram/releases/tag/update](https://github.com/ergoncugler/web-scraping-telegram/releases/tag/update) / And also, to make things easier, directly on Google Colab, just play it (In Colab it is possible to run 'async' without needing 'def'):
[https://colab.research.google.com/drive/1lzn_XomUI9uCMLkGjQf6-2JnkKazgevh?usp=sharing](https://colab.research.google.com/drive/1lzn_XomUI9uCMLkGjQf6-2JnkKazgevh?usp=sharing)
